name: Angular GitHub CI
on:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 18.x
        uses: actions/setup-node@v1
        with:
          node-version: 18.x

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: test-github-flow/node_modules
          key: ${{ runner.os }}-node-18.x-${{ hashFiles('test-github-flow/**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-18.x-
            ${{ runner.os }}-node-
            ${{ runner.os }}-

      - name: Install Dependencies
        run: |
          npm ci

      - name: Build
        run: |
          cd test-github-flow
          npm run build

      - name: Lint
        run: |
          cd test-github-flow
          npm run lint

      - name: Test
        run: |
          cd test-github-flow
          npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
